### ISSUE TITLE
Compiled dependencies

### ISSUE THREAD

**Issue by fabiosantoscode** [secure-require/secure-require#9]
Hey there!

What is the plan for secure-require and compiled dependencies?

If someone ships a module written in C++ to npm (without requiring any node core dependencies), couldn't that someone escape the sandbox? Or at least write anything to the filesystem using POSIX APIs, open TCP sockets etc from C++?

For example, let's suppose you use Terser with secure-require on your server, but a bad actor has gained publish rights to one of Terser's dependencies (or Terser itself). Wouldn't they be able to add C++ code to this dependency that then runs natively and freely on your machine?

**Comment by ryzokuken** [comment]
Yes, they can and yes, there’s nothing we’re currently doing about it.

About thinking about it deeply for a while, I realized that it was too big a fish to fry all by myself. It would take a lot of work to develop a security model for native modules, and I decided to keep it as a non-goal for now. In case you have suggestions or ideas, please feel free to let me know. I failed to come up with any unfortunately. That said, I’ll be closing this for now. Feel free to reopen!

**Comment by fabiosantoscode** [comment]
I agree that coming up with and implementing a security model for native modules would be an insane task to tackle!

I suggest that secure-require simply block requires of native modules in case it is not doing it already.

**Comment by ryzokuken** [comment]
@fabiosantoscode sounds fair. Would you like to make a PR for this?
